In [0]:
import tensorflow as tf
import numpy as np

In [0]:
a = np.array([1010, 1000, 990]) 
print(a)

[1010 1000  990]


In [0]:
def softmax(a):
  exp_a = np.exp(a)
  sum_exp = np.sum(exp_a)
  y = exp_a / sum_exp
  return y

In [0]:
softmax(a) # 지수함수를 사용하기 때문에 오버플로우 발생 

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.


array([nan, nan, nan])

In [0]:
def softmax_new(a):
    c = np.max(a)
    exp_a = np.exp(a - c)
    sum_exp = np.sum(exp_a)
    y = exp_a / sum_exp
    return y

In [0]:
softmax_new(a)

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])

In [0]:
# tensorflow에 구현된 softmax 확인 
# overflow 방지되어있음

In [0]:
a = tf.constant(np.array([1010, 1000, 990]).astype(np.float64))

sess = tf.Session() 
sess.run(tf.nn.softmax(a))

array([9.99954600e-01, 4.53978686e-05, 2.06106005e-09])